import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import './globals.css';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status === 'loading') {
    return <div>Loading...</div>;
  }

  if (!session && router.pathname !== '/auth/login' && router.pathname !== '/auth/register') {
    router.push('/auth/login');
  }

  return (
    <html lang="en">
      <head>
        {/* Outros meta dados e links */}
      </head>
      <body className={inter.className}>
        {session ? (
          <div className="d-flex">
            <Navbar />
            <main className="main-content flex-grow-1 p-4">{children}</main>
          </div>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
